version: '3'
services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://mongo:27017/parser
  db:
    image: mongo
    restart: always
    container_name: db
    volumes:
      - c64942bcc46cdd1f81a929c165e2bc80ae0f610cb221380c5ac4711071c54797:/data/db
    ports:
      - "27017:27017"
volumes:
  c64942bcc46cdd1f81a929c165e2bc80ae0f610cb221380c5ac4711071c54797:
    external: true
  